maltsev/htmlnano

package.json

Windows machines are not able to work with `rm` command and do not work correctly with the `./node_modules` in npm scripts.

Cross-platform build of project

---

README.md
lib/modules/removeRedundantAttributes.es6
test/modules/removeRedundantAttributes.js

Source: https://developer.mozilla.org/ru/docs/Web/HTML/Element/button
> The type of the button. Possible values are:
>   * **submit**: The button submits the form data to the server. **This is the default if the attribute** is not specified, or if the attribute is dynamically changed to an empty or invalid value.

Remove redundant attribute type="submit" from <button>

---

.gitignore
README.md
lib/htmlnano.es6
lib/modules/collapseWhitespace.es6
test/htmlnano.js
test/modules/collapseWhitespace.js
test/usage.js

This should be a safe default, as found when working on Parcel.
Also improves collapseWhitespace `conservative` mode slightly, to remove spaces from the topLevel and only insert single space if the code already had a space in that place
Closes #50

Default to safe transforms

---

README.md
lib/helpers.es6
lib/htmlnano.es6
lib/modules/collapseBooleanAttributes.es6
lib/modules/mergeStyles.es6
lib/modules/minifyCss.es6
test/helpers.js
test/modules/collapseBooleanAttributes.js
test/modules/mergeStyles.js
test/modules/minifyCss.js

Related issue: #57
- `mergeStyles` and `minifyCss` now ignores the AMP boilerplate (`<style amp-boilerplate>...</style>`).
- Added test to ensure `mergeStyles` preserves `amp-custom` attribute.
- Added `allowpaymentrequest` and `allowtransparency` to `collapseBooleanAttributes` (not AMP related).
- Added AMP-specific boolean attributes to `collapseBooleanAttributes`. These will only be collapsed when empty, since some of them are not exclusively boolean and this functionality needs to enabled via an option for this module.
- Updated README.

Add support for AMPHTML.

---

.travis.yml

Removed node versions 4 and 5 from `.travis.yml`, added 6.

Remove old node versions from Travis

---

package.json

Per #49, tests are failing due to a leak in one of the dependencies.
Removing leak checking should at least make Travis more useful until #49 is fixed. We can revert this PR after that.

Remove leak checking from mocha

---

lib/presets/ampSafe.es6

Turns out it causes issues with valid AMP like `<button on="tap:something">` as it removes the `tap:`. Also not really needed since AMP has no custom JavaScript in the HTML.

Disable minifyJs for ampSafe

---

lib/modules/collapseBooleanAttributes.es6

It seems there's an edge-case where another posthtml plugin produces (I believe valid) tree that looks like this:
```
{
tag: false,
attrs: {
something: 'abc'
},
content: [
...
]
}
```
In this case, a placeholder element was replaced by changing `tag` to false, but the `attrs` property remained. This cases `collapseBooleanAttributes` to throw `TypeError: node.tag.search is not a function` since `node.tag` is a boolean and doesn't have the `search` property.

Fix bug when tag === false

---

lib/modules/collapseBooleanAttributes.es6

> An invalid keyword and an empty string will be handled as the `anonymous` keyword.
[Source](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes)

Add "crossorigin" to boolean attributes

---

README.md
lib/helpers.es6
lib/modules/minifyCss.es6
lib/modules/removeUnusedCss.es6
lib/presets/max.es6
lib/presets/safe.es6
package.json
test/helpers.js
test/modules/removeUnusedCss.js

Fixes #36.
I originally wanted to make this part of `minifyCss`, but that'd break compatibility (since the module options would need to include both options for cssnano and for uncss).
This seems to work well based on a few tests. Might be an overkill in terms of performance, but I think it's a good idea to rely on a field-tested library like uncss.

Add removeUnusedCss module (uncss based)

---

lib/helpers.es6
lib/htmlnano.es6
lib/modules/collapseBooleanAttributes.es6
lib/modules/mergeScripts.es6
lib/modules/minifyJs.es6
lib/modules/removeRedundantAttributes.es6
lib/modules/removeUnusedCss.es6
lib/presets/ampSafe.es6
lib/presets/max.es6

- Use spread syntax replacing Object.assign
- When first parameter of `Object.assign` is an empty plain object, it will be slower than spread syntax.
- Spread in object literals is an ES2018 feature and is supported since Node.js 8.3.0.
- Use `const` instead of `let` in `for..of` loop
- Unit tests are passed & eslint is happy

Adopt some ES6 syntaxs

---

README.md
lib/modules/collapseWhitespace.es6
package.json
test/modules/collapseWhitespace.js

I would like to propose an addition/change to the 'collapseWhitespace' plugin to more aggressively remove semantically redundant whitespace.
I saw, looking at the output of my minified code, lots of spaces being introduced where none existed in my input. These turned out to be a translation of the indentation/newlines into a single space. Since almost all of the markup was structural none of those spaces were adding anything of value.
Therefore I suggest that a new 'aggressive' mode be introduced that removes structural/incidental whitespace such as this. Actual space characters can be collapsed but should not be removed as they are essential between inline tags (e.g. title&lt;/b&gt; &lt;i&gt;part).
This pull request is a first attempt at implementing such behaviour.
Is this something you …

Add a more aggressive whitespace removal option to the collapseWhitespace plugin

---

lib/modules/sortAttributesWithLists.es6
lib/presets/safe.es6
test/modules/sortAttributesWithLists.js

The feature won't impact the plain-text size of the output. It is designed to improve the compression ratio of gzip/brotli used in HTTP compression since it forms long repetitive chains of characters.
The document will be updated by another PR after this one is merged.

Feat: sort values inside list-like attributes

---

README.md

Add documents for #95.
BTW, I notice that the [contributing guide](https://github.com/posthtml/htmlnano#contribute) is outdated. There is no `the modules array` anymore, modules are now loaded automatically according to `options` and `presets`. I can bring up another PR to update the contributing guide.

Docs: add sortAttributesWithLists

---

README.md

There is no `the modules array` anymore. Modules are now loaded automatically according to `options` and `presets` since `0.2.0`.

Docs: update contributing guide

---

README.md
lib/modules/removeRedundantAttributes.es6
test/modules/removeRedundantAttributes.js

`type=text/css` is redudant for `link[rel=stylesheet]`. The PR introduces the feature to `removeRedundantAttributes` module.

Feat: remove "type=text/css" for link[rel=stylesheet]

---

README.md
lib/modules/removeAttributeQuotes.es6
lib/presets/max.es6
lib/presets/safe.es6
test/modules/removeAttributeQuotes.js

Closes #6 
Implement a module that will be able to access and modify `tree.options.quoteAllAttributes`.
Notice it is not safe to changing `tree.options` directly (although PostHTML Team doesn't think so). I have already discussed it with PostHTML Team (https://github.com/posthtml/posthtml/issues/335). There should be a better approach.

Feat: removeAttributeQuotes

---

test/modules/minifyUrls.js

#104 introduces `removeAttributesQuotes` and being enabled in max preset.
Since `minifyUrls` includes max preset during testing, the change has to be made.

Fix: minifyUrls test cases with maxPreset

---

README.md
lib/modules/collapseWhitespace.es6
test/modules/collapseWhitespace.js

#103.
Removing more and less (explanation below) white spaces for `aggressive` mode, results in an even smaller size of outputs.
After the PR, it will be unlikely for `aggressive` mode to break the page.

Refactor: trim more whitespaces for aggressive mode

---

lib/modules/collapseBooleanAttributes.es6
test/modules/collapseBooleanAttributes.js

Add back collapse `crossorigin` attributes again.
Instead of treat `crossorigin` as a Boolean attribute, now `crossorigin` will only be collapsed if `crossorigin='anonymous'` or `crossorigin=''`. So `crossorigin='use-credentials'` will not be affected.
cc @Oloompa @fstanis 
Ref: #78 #79

Feat: collapse crossorigin attributes

---

lib/modules/removeComments.es6
test/modules/removeComments.js

Exclude excerpt comment for common CMS:
- Hexo: https://hexo.io/docs/tag-plugins#Post-Excerpt
- Hugo: https://gohugo.io/content-management/summaries/#manual-summary-splitting
- WordPress: https://wordpress.com/support/wordpress-editor/blocks/more-block/2/
- Jekyll: https://jekyllrb.com/docs/posts/#post-excerpts

Feat: exclude excerpt comment

---

README.md
lib/modules/removeOptionalTags.es6
lib/presets/max.es6
lib/presets/safe.es6
test/modules/removeOptionalTags.js

#29.
Due to the limitation of PostHTML (#99), only `html`, `head`, `body`, `colgroup`, `tbody` are supported, since only their start tag (opening tag) & end tag (closing tag) can be omitted at the same time.

Feat: removeOptionalTags

---

README.md
lib/modules/sortAttributesWithLists.es6
lib/presets/safe.es6
test/modules/sortAttributesWithLists.js

#86.
Support sort list-like attribute values by frequency.
Now `sortAttributesWithLists` configuration accept following values:
- `alphabetical`
- `frequency`
Old configuration `true` will be considered as `alphabetical`, thus no breaking changes being introduced.

Feat: support sort list-like attribute values by frequency

---

lib/modules/collapseWhitespace.es6
test/modules/collapseWhitespace.js

```html
<div> <span> </span> </div>
```
The whitespace between `<div>` & `<span>` and the whitespace between `</span>` & `</div>` are save to remove:
```html
<div><span> </span></div>
```
The PR implements it.

Feat: strip more spaces for collapseWhitespace

---

package.json

`posthtml` is targeting `Node.js > 10`. Thus we only need babel to transform ES Module to CommonJS Module. By adding `targets.node: 10` we can avoid unnecessary transformation & polyfill.

Chore: update babel configuration

---

lib/modules/collapseWhitespace.es6
test/modules/collapseWhitespace.js

```html
<a>Link</a> <div></div>
```
The whitespace between `</a>` & `<div>` is safe to remove, since `<a>` is an inline element while `<div>` is a block element.

Feat: strip whitespaces between textnode & element

---

lib/modules/collapseWhitespace.es6
lib/modules/removeOptionalTags.es6

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Character_Classes):
> `\s` matches a single white space character, including space, tab, form feed, line feed, and other Unicode spaces. Equivalent to `[ \f\n\r\t\v\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff]`.

Refactor: normalize regex pattern

---

lib/modules/collapseWhitespace.es6

Due to a recent change from posthtml-parser (https://github.com/posthtml/posthtml-parser/commit/8e64082e9d084bcf42e100ef69c9af76132ff544), the comment is now parsed differently: 
```html
'<div>    <div>'
```
will be parsed as:
```diff js
{content:
-  ["  ", "", "  ", Object {tag: "div"}] // before
+  ["  ", "  " // now
, tag: "div"}
```
The PR is to adapt to the behavior changes.
> After `rm -rf node_modules && npm i`, I notice that `npm test` no longer passes. Then I found out the behavior changes and bring up the PR. It is not a bug fix since it is only related to unit tests.

Fix: collapseWhitespaces around comment

---

lib/modules/collapseWhitespace.es6

After #116, there is no need to treat whether a text node only contains white spaces or not. The PR simplifies the related logic.

Refactor: simplify the logic of collapseWhitespaces

---

lib/modules/minifyCss.es6
lib/modules/minifyJs.es6
test/modules/minifyCss.js
test/modules/minifyJs.js
test/modules/minifySvg.js

Fix: #88 & CDATA inside script/style

---

lib/modules/minifySvg.es6
lib/modules/removeUnusedCss.es6
package.json

`tree` already has its own `render` property, use it instead.

Refactor: remove posthtml-render dependency

---

README.md
lib/modules/minifyConditionalComments.es6
test/modules/minifyConditionalComments.js

With a dirty hack, [the limitation of PostHTML](https://github.com/posthtml/posthtml-parser/issues/9) (which is actually a issue from upstream [htmlparser2](https://github.com/fb55/htmlparser2/pull/146)) has been bypassed.

Fix: minifyConditionalComment with <html> support

---

lib/modules/minifyJs.es6
lib/modules/removeRedundantAttributes.es6

[`tree.match`](https://github.com/posthtml/posthtml/blob/df802455e5b151fe80ceb3d509fef3bdd6f78e99/lib/api.js#L81-L95) will actually traverse through `tree` to find the matches according to its implementation, thus two `tree.match` means traverse through `tree` twice. By refactoring the code to `tree.walk` the `tree` will be traversed only once.

Perf: improve the performance of minifyJs

---

lib/htmlnano.es6
test/htmlnano.js

For bundlers like Parcel it's usually a good thing to be able to opt-out of config loading so we can allow our users to use a memory filesystem, browser-compatibility and reliable caching.
Alternatively we could do something like this:
```js
// loads the config, returning the filepath, options and preset
export function loadConfig(options, preset) {}
// runs htmlnano as it did before the config introduction
export function htmlnanoCore(options, preset) {}
// loads config and runs htmlnanoCore
export function htmlnano(options, preset) {}
```

Add the ability to skip config loading entirely

---

docs/docs/050-modules.md
lib/presets/safe.es6
package.json
test/modules/minifySvg.js

I hit the same issue as #150, ended up with the same fix as #151 but hopefully complete (the only remaining reference is in versioned_docs, which I guess is a historic snapshot that shouldn't be changed?)

Avoid deprecated SVGO function

---

docs/docs/050-modules.md
lib/modules/removeComments.es6
test/modules/removeComments.js

This implements #73
I'd like to introduce more options (like `whiteList` and `blackList`), which will require the `removeComments` module option to be an object. So I'd prefer to leave those changes to the next major version of htmlnano so that we can introduce it as a breaking change.
Also, cc @SoftCreatR

Feat: custom matcher for removeComments module

---

lib/modules/minifyJs.es6
lib/modules/minifyUrls.es6
test/modules/minifyUrls.js

- Update `minifyJs` wrapper, to prevent tree shaking from strip the entire function.
- Update `minifyUrl` to support javascript URL minification.

Feat: minifyJs and minifyUrls enhancement

---

lib/modules/collapseWhitespace.es6
test/modules/collapseWhitespace.js

TL; DR: This closes #145.
Long description:
The PR handles an edge case when a `noTrimWhitespacesInsideElement` is right next to a `noTrimWhitespacesArroundElement`, and both of them have the text content surrounded by whitespace. The previous implementation is simply keeping those whitespaces, result in redundant whitespaces.
cc @thewilkybarkid

Fix: enhance collapse whitespace (#145)

---

docs/docs/050-modules.md
lib/modules/normalizeAttributeValues.es6
lib/presets/safe.es6
test/modules/normalizeAttributeValues.js

Feat: normalize attribute

---

lib/modules/removeRedundantAttributes.es6
test/modules/removeRedundantAttributes.js

In the spec, some attributes have `missing value default` (default state when an empty string is provided). This can be used to reduce output size even further.

Feat: collapsing missing value default attribute

---

docs/docs/050-modules.md
lib/helpers.es6
lib/htmlnano.es6
lib/modules/minifyCss.es6
lib/modules/minifyJs.es6
lib/modules/minifySvg.es6
lib/modules/minifyUrls.es6
lib/modules/removeUnusedCss.es6
package.json
test/helpers.js
test/htmlnano.js

Fix #165, close #166.
Make `terser`, `cssnano`, `uncss`, etc. optional.
**BREAKING CHANGES**
Only merge it when it is about to bump a major version.
----
@maltsev What about creating a new branch `v2`? I'd like to introduce other breaking changes on top of this PR (like making `purgecss` default instead of `uncss`). With a new branch, we can only merge breaking changes into `master` when `2.0.0` is about to release.

Feat: supports optional dependencies

---

lib/presets/max.es6
lib/presets/safe.es6
test/modules/mergeScripts.js
test/modules/mergeStyles.js

Consider a case:
```html
<template>
<script>/* I shouldn't be executed when page is loaded! */</script>
</template>
```
htmlnano's `mergeScripts` and `mergeStyles` can't detect such a case and may cause unwanted behaviors by extracting and merging them to the top level.
There are many ways for a developer to make their own template (E.g. `<script type="mySecretTemplate"><script>/* I shouldn't be executed when page is loaded! */</script></script>`) and there is no way for htmlnano can identify them all. Thus those two features should be disabled in v2 by default.
Those two features can retain enabled by default in v1 since we haven't received any bug reports about the issue, yet.

Disable mergeScripts & mergeStyles in safe preset

---

lib/htmlnano.es6
lib/modules/collapseAttributeWhitespace.es6
lib/modules/collapseBooleanAttributes.es6
lib/modules/deduplicateAttributeValues.es6
lib/modules/example.es6
lib/modules/minifyJson.es6
lib/modules/normalizeAttributeValues.es6
lib/modules/removeComments.es6
lib/modules/removeEmptyAttributes.es6
lib/modules/removeRedundantAttributes.es6

I create a draft PR since It is just a Proof of Concept for #127. The PR is meant to allow for discussion and showing some refactoring issues going on.

Feat: implements #127

---

lib/htmlnano.es6
lib/modules/minifyJson.es6
lib/modules/minifySvg.es6

The PR closes #182.
X-Ref: https://github.com/parcel-bundler/parcel/issues/7906
PostHTML does supports `node.content` to be either a `string` or a `string[]` when stringify a PostHTML AST Tree into HTML, while PostHTML parser will only emit `node.content` as an array of string. So the new htmlnano module syntax (#128) just take it for granted that `node.content` will always be a `string[]`.
However, some htmlnano modules (`minifyJson` and `minifySvg`) will transform `node.content` into a `string` instead of a `string[]`, so when other modules (which expects `node.content` to be a `string[]`) process the new `node.content` later on, htmlnano will crash.
This PR fixes the issue by:
- Make sure `minifyJson`, `minifySvg`, and other modules will always return `string[]`.
- `node.content` will …

Fix(#182): correct types and type checks

---

lib/helpers.es6
lib/modules/collapseWhitespace.es6
test/modules/collapseWhitespace.js

Fix a very rare edge case that `collapseWhitespace` module wrongly trim a whitespace when `removeComments` module is disabled. This PR makes sure the whitespace will not be trimmed when `prevNode` or `nextNode` is text nodes (or comments).

Fix(collapseWhitespace): handle textNode when comment is preserved

---

lib/modules/minifyUrls.es6
package.json
test/modules/minifyUrls.js

The PR fixes:
- `srcset@5.0.0` is a pure ESM package which can not be used inside a CommonJS package. Downgrade `srcset` to `4.0.0` and has version pinned.
- Fix `javascript:` URL can not be minified properly.
- Fix the test cases

Fix(minifyUrl): srcset & javascript URL minify issue

---

docs/docs/020-usage.md

[`gulp-htmlnano`](https://github.com/posthtml/gulp-htmlnano) is not actively maintained and is kinda deprecated. And even gulp itself is not actively maintained anymore.
Encourage developers to use [`gulp-posthtml`](https://github.com/posthtml/gulp-posthtml) along with the latest version of posthtml & htmlnano.

Docs(usage): encourage using gulp-posthtml instead of gulp-htmlnano

---

docs/docs/050-modules.md
lib/modules/collapseBooleanAttributes.es6
lib/modules/normalizeAttributeValues.es6
lib/modules/removeRedundantAttributes.es6
lib/presets/safe.es6
test/modules/collapseBooleanAttributes.js
test/modules/normalizeAttributeValues.js
test/modules/removeRedundantAttributes.js

The PR closes https://github.com/posthtml/htmlnano/issues/68
- Per HTML5 spec, the empty string value attribute can be collapsed (`[a=""] => [a]`). 
- Add support for HTML5 spec's invalid value default normalization
- Make sure attributions are normalized before being collapsed.
- `custom` plugin will be the last to applied.
The docs are also updated. Now the order of modules' documentation are sorted.
The PR should also further increases the minify rate. The benchmark might need an update as well.

Feat: further minify attribute values

---

docs/versioned_docs/version-2.0.0/030-config.md

There's a typo in 030-config.md for the configuration file "htmlanorc.json". This PR simply fixes said typo.

Fixing Configuration File Typo

---

lib/modules/minifySvg.es6
test/modules/minifySvg.js

The PR fixes #197.
htmlnano will return the SVG node as is when svgo encounters an error, and show error information to `stderr`.

Fix(#197): do not choke on svg error

---

lib/modules/minifyJs.es6
test/modules/minifyJs.js

When minify JS with options `minifyJs: { module: true }` then it minifies the attrs wrapper functions too.
from `function a(){ ... }a();` to `!function(){ ... }()`
It broke the code because the wrapper function changes the length
source:
```html
<video oncanplay="this.currentTime = 1.2; this.oncanplay=null;"></video>
```
minify: (cut off the first and the list symbol)
```html
<video oncanplay="his.currentTime=1.2,this.oncanplay=nul"></video>
```
To fix, use a function expression. It doesn't change by minification

Fix js minify attrs value

---

lib/modules/mergeScripts.es6
lib/modules/mergeStyles.es6
lib/modules/minifyCss.es6
lib/modules/minifyJs.es6
lib/modules/minifyJson.es6
test/modules/mergeScripts.js
test/modules/mergeStyles.js
test/modules/minifyCss.js
test/modules/minifyJs.js
test/modules/minifyJson.js

The PR fixes #220.
The PR makes htmlnano skip any `<script />` and `<style />` tags that have SRI attributes, including `minifyJs`, `minifyCss`, `minifyJson`, `mergeStyles` and `mergeScripts`.
The reason behind the change is documented in the comment, and test cases about the change are also added.

fix(#220): skip <script> and <style> with SRI

---

lib/htmlnano.es6
test/htmlnano.js

Fix `Module "skipConfigLoading" is not defined` error when run:
```javascript
htmlnano.process(html, { skipConfigLoading: true });
```

remove `skipConfigLoading` from options after used.

---

lib/modules/collapseWhitespace.es6

This prevents replacement of significant (non-ASCII) whitespace like (non-entity-encoded) non-breaking spaces, etc.

collapse whitespace according to spec

---

lib/modules/collapseWhitespace.es6

Sorry, I had misread the spec. Tests are now passing.

fix misread "one or more" as "more than one" from spec

---

lib/helpers.mjs
test/modules/minifyConditionalComments.mjs
test/modules/removeComments.mjs

The closing comment for [downlevel-revealed closing comments](https://en.wikipedia.org/wiki/Conditional_comment#Downlevel-revealed_conditional_comment) were being deleted in safe mode. Added one more test and fixed a falsely passing test.
I'm using htmlnano for minifying the output from mjml and noticed that even in safemode, the closing comments for some conditional comments were being removed.

fix: fix downlevel-revealed closing comment being deleted in safe mode

---

docs/docs/050-modules.md
index.d.ts
test/modules/removeComments.mjs

According to tests and documentation, the `comment` argument is missing from the TypeScript definition of the `removeComments` option.
https://github.com/posthtml/htmlnano/blob/151da26bf6b1e82e380ace889bcf8da6e34f7976/test/modules/removeComments.mjs#L125-L128
https://github.com/posthtml/htmlnano/blob/151da26bf6b1e82e380ace889bcf8da6e34f7976/index.d.ts#L25
Also, I used the singular form since each comment is processed individually.

fix: add missing argument in typescript definition of removeComments

---

package.json

Ran into #270 myself; I'm not a user of Typescript directly, but I do grab types using JSDoc comments to help in my IDE. Did some research, apparently you have to declare explicit type exports in `package.json`.
Specifically, I followed the work done in this comment here: https://github.com/tj/commander.js/pull/1704#issuecomment-1070359858. I then did a local install to verify type accquisition works as intended and it appears to. Hopefully this pull request fixes it!

fix(types): add exports to package.json

---

index.d.ts
lib/htmlnano.mjs

motivation:
I'm using htmlnano with AWS Lambda, where the `console.warn` shows in unit tests and AWS cloudwatch. To suppress them, an optional flag is required

feat: add skipInternalWarnings flag to avoid console.warn output
