lib/modules/minifyCss.es6
We were getting styleNode.content.join is not a function on some inputs
=> handle content as String in addition to Array

lib/modules/collapseBooleanAttributes.es6
=> Remove crossorigin from boolean attribute

README.md, lib/modules/collapseWhitespace.es6
A couple of small cleanups from the review: https://github.com/posthtml/htmlnano/pull/90
=> Code review feedback for aggressive whitespace plugin

lib/modules/removeComments.es6, test/modules/removeComments.js
Support Cloudflare's Server Side Exclude feature for `removeComments`.
https://support.cloudflare.com/hc/en-us/articles/200170036-What-does-Server-Side-Excludes-SSE-do-
=> Feat: removeComments supports Cloudflare SSE

lib/modules/minifyUrls.es6, lib/presets/safe.es6, package.json, test/modules/minifyUrls.js
The PR closes #10.
The document will be updated in another PR after this one is merged.
P.S.
> Let me know when the docs are ready then I'll release a new version of htmlnano.  https://github.com/posthtml/htmlnano/pull/95#issuecomment-706500154
I'm also refactoring `Object.keys` into `Object.entries` which will land in another PR. That PR should be included in the new release as well.
=> Feat: bring up minifyUrls

README.md
=> Docs: add minifyUrls

lib/htmlnano.es6, lib/modules/collapseAttributeWhitespace.es6, lib/modules/mergeScripts.es6, lib/modules/minifyUrls.es6, lib/modules/removeEmptyAttributes.es6, lib/modules/removeRedundantAttributes.es6
- Utilize Object.entries & Object.values
- Bring constants to the top
- Improve minifyUrls' performance by changing `tree.walk` to `tree.match`
=> Refactor: some minor changes

README.md, lib/modules/sortAttributes.es6, lib/modules/sortAttributesWithLists.es6, lib/presets/safe.es6, package.json, test/modules/sortAttributes.js
Closes #86. Sorts attributes inside elements.
cc @MathGeniusJodie
=> Feat: sortAttributes

lib/modules/minifyUrls.es6, package.json, test/modules/minifyUrls.js
=> Feat: add source[src] & srcset support to minifyUrls

lib/helpers.es6, lib/modules/collapseBooleanAttributes.es6, lib/modules/collapseWhitespace.es6, lib/modules/deduplicateAttributeValues.es6, lib/modules/minifyCss.es6, lib/modules/minifyJs.es6, lib/modules/minifySvg.es6, lib/modules/minifyUrls.es6, lib/modules/removeRedundantAttributes.es6, lib/modules/sortAttributes.es6, lib/modules/sortAttributesWithLists.es6
- Performance improvements
- Adapt to ES6 `String@startsWith`
- Simplify and clean up
=> Refactor: overall improvements

lib/modules/minifySvg.es6, test/modules/minifySvg.js
=> Fix: minify svg correctly (#129)

package.json
=> [WIP] Upgrade to posthtml@0.16.0 + fix

README.md, uncss-fork.patch
Adds patch file to allow swapping uncss with fork.
Closes #152
=> Add option to use uncss fork

docs/docs/050-modules.md, lib/helpers.es6, lib/modules/collapseAttributeWhitespace.es6, lib/modules/minifyJs.es6, test/modules/collapseAttributeWhitespace.js
Some single-valued attributes can be trimmed to further reduce output size.
=> Feat: enhanced attribute collapse whitespace

lib/modules/collapseAttributeWhitespace.es6, test/modules/sortAttributesWithLists.js
=> Fix(#180): exclude "sizes" from attributesWithLists

docs/docs/020-usage.md, lib/htmlnano.es6, test/htmlnano.js
Export `htmlnano.htmlMinimizerWebpackPluginMinify` for usage with `HtmlMinimizerWebpackPlugin`.
=> Feat: support usage with webpack

lib/modules/sortAttributes.es6, test/modules/sortAttributes.js
=> Fix(#189): incorrectly handle empty attribute value

index.d.ts, package.json
Ref: #201
Continuation of #203, add better type for plugins' options.
=> Better TypeScript definition

lib/modules/normalizeAttributeValues.es6
The PR fixes https://github.com/parcel-bundler/parcel/issues/8828
=> Fix: remove autocomplete from normalizeAttributeValue

eslint.config.mjs, package.json, src/_modules/minifyCss.ts, src/_modules/minifyJs.ts, src/index.ts, test/helpers.ts
Fixes #373, also some other minor changes to make ESLint happy.
=> Fix(#373): interop dynamically imported htmlnano module properly
